upstream rest_api    { server rest_api:8999; }
upstream auth        { server auth:8905; }
upstream keeper      { server keeper:8973; }
upstream ngui        { server ngui:4000; }
upstream herald      { server herald:8906; }
upstream katara      { server katara:8935; }
upstream insider_api { server insider_api:8945; }
upstream slacker     { server slacker:80; }
upstream metroculus_api { server metroculus_api:8969; }
upstream jira_bus    { server jira_bus:8977; }
upstream jira_ui     { server jira_ui:4000; }
upstream diproxy     { server diproxy:8935; }
upstream subspector  { server subspector:8800; }

server {
    listen 80;
    server_name _;

    client_max_body_size  512m;
    proxy_read_timeout    600;
    proxy_send_timeout    600;
    proxy_connect_timeout 60;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /auth {
        proxy_pass http://auth;
    }

    location /restapi {
        proxy_pass http://rest_api;
    }

    location /report {
        proxy_pass http://keeper;
    }

    location /herald {
        proxy_pass http://herald;
    }

    location /katara {
        proxy_pass http://katara;
    }

    location /insider {
        proxy_pass http://insider_api;
    }

    location /slacker {
        proxy_pass http://slacker;
    }

    location /metroculus {
        proxy_pass http://metroculus_api;
    }

    location /jira_bus {
        proxy_pass http://jira_bus;
    }

    location /jira_ui {
        proxy_pass http://jira_ui;
    }

    location /storage {
        proxy_pass http://diproxy;
    }

    location /subspector {
        proxy_pass http://subspector;
    }

    location / {
        proxy_pass http://ngui;
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
    }
}
