skip_config_update: false
drop_tasks_db: false
databases:
  - auth-db
  - my-db
  - tasks
  - herald
  - katara
  - slacker
  - jira-bus
  - subspector

etcd:
  public_ip: ""
  company_name: "Hystax"
  product_name: "OptScale"
  encryption_key: ""
  release: "docker-compose"
  katara_scheduler_timeout: 3600
  bumi_scheduler_timeout: 300
  bumi_worker:
    max_retries: 5
    wait_timeout: 7200
    task_timeout: 3600
    run_period: 10800
  optscale_service_emails:
    recipient: ""
    enabled: false
  optscale_error_emails:
    recipient: ""
    enabled: false
  skip_email_filters: {}
  google_calendar_service:
    enabled: false
    access_key:
      type: ""
      project_id: ""
      private_key_id: ""
      private_key: ""
      client_email: ""
      client_id: ""
      auth_uri: ""
      token_uri: ""
      auth_provider_x509_cert_url: ""
      client_x509_cert_url: ""
  domains_blacklists:
    new_employee_email: []
    registration: []
    failed_import_email: []
  domains_whitelists:
    new_employee_email: []
    registration: []
    failed_import_email: []
  secret:
    cluster: "bebeadf5e7fb25a82395016ac198d860fcb18217f2f9c18a22fd4deb97b57c6e"
    agent: ""
  images_source:
    host: ""
    tag: "local"
  restapi:
    invite_expiration_days: 30
    host: rest_api
    port: 8999
    demo:
      multiplier: 2
    report_imports:
      not_processed_threshold_secs: 10800
      message_expiration_secs: 10800
  auth:
    host: auth
    port: 8905
  katara:
    host: katara
    port: 8935
  herald:
    host: herald
    port: 8906
  keeper:
    host: keeper
    port: 8973
  insider:
    host: insider_api
    port: 8945
  slacker:
    host: slacker
    port: 80
  jirabus:
    host: jira_bus
    port: 8977
  metroculus:
    host: metroculus_api
    port: 8969
  thanos_query:
    host: thanos-query
    port: 10902
  thanos_receive:
    host: thanos-receive
    port: 19291
    path: api/v1/receive
  authdb:
    host: mariadb
    user: root
    password: "my-password-01"
    db: auth-db
  heralddb:
    host: mariadb
    user: root
    password: "my-password-01"
    db: herald
  restdb:
    host: mariadb
    user: root
    password: "my-password-01"
    db: my-db
    port: 3306
  kataradb:
    host: mariadb
    user: root
    password: "my-password-01"
    db: katara
  slackerdb:
    host: mariadb
    user: root
    password: "my-password-01"
    db: slacker
    port: 3306
  jirabusdb:
    host: mariadb
    user: root
    password: "my-password-01"
    db: jira-bus
    port: 3306
  subspectordb:
    host: mariadb
    user: root
    password: "my-password-01"
    db: subspector
    port: 3306
  mongo:
    url: "mongodb://root:SecurePassword-01-02@mongo:27017"
    database: keeper
  influxdb:
    host: influxdb
    port: 8086
    user: ""
    pass: ""
    database: metrics
  rabbit:
    user: "optscale"
    pass: "secure-password-here"
    host: rabbitmq
    port: 5672
  minio:
    host: minio
    port: 9000
    access: "optscale-minio"
    secret: "secret_password"
  clickhouse:
    host: clickhouse
    port: 8123
    user: "default"
    password: "secure-password-1-clk"
    db: "default"
  cleanmongodb:
    chunk_size: 500
    rows_limit: 10000
    archive_enable: ""
    file_max_rows: 10000
  disable_email_verification: "True"
  force_aws_edp_strip: ""
  encryption_salt: ""
  encryption_salt_auth: ""
  logstash_port: 12201
  events_queue: "events_queue"
  resources_discovery_cache_time: ""
  overlay_list: ""
  token_expiration: 168
  users_dataset_generator:
    enable: false
    bucket: ""
    s3_path: ""
    filename: ""
    aws_access_key_id: ""
    aws_secret_access_key: ""
  service_credentials: {}
  smtp:
    server: ""
    email: ""
    login: ""
    port: ""
    password: ""
    protocol: "SSL"
  resource_discovery_settings:
    discover_size: 10000
    timeout: ""
    writing_timeout: 60
    observe_timeout: 7200
    debug: ""
  bi_settings:
    exporter_run_period: 86400
    encryption_key: "5t3X3PkQqF5edqW9_c8znow7k7GraZOpBLHhF1kFFvE="
    task_wait_timeout: 259200
  failed_imports_dataset_generator:
    enable: false
    bucket: ""
    s3_path: ""
    filename: ""
    aws_access_key_id: ""
    aws_secret_access_key: ""
  subspector:
    host: subspector
    port: 8800
  password_strength_settings:
    min_length: ""
    min_lowercase: ""
    min_uppercase: ""
    min_digits: ""
    min_special_chars: ""
  demo_org_cleanup:
    demo_org_lifetime_hrs: ""
  diworker:
    max_report_imports_workers: 10
  exchange_rates:
    BRL: ""
    INR: ""
    EUR: ""
  stripe:
    api_key: ""
    webhook_secret: ""
    enabled: false
  certificates: {}
